version: '3.0'

services:
  flashcard-db:
    container_name: flashcard-db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres#1234
      POSTGRES_DB: flashcardDEV
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-data: